### ISSUE TITLE
ogpの設定がちゃんとされていない

### ISSUE THREAD

**Issue by kaz1104** [nttcom/remote-work-handbook#5]
テンプレートいじればどうとでもなる…はず？
Shinesで公開する前には何とかしておきたい気がする。（宣伝されてシェアされる可能性も出てくるので。）

**Comment by ppyv** [comment]
HugoによるとOpen graphの実装方法についてはここを参照とのこと。
https://gohugo.io/templates/internal/

必要とされている `<head>` 内へのスニペット (`{{ template "_internal/opengraph.html" . }}`) は現行のテーマでも実装済み。
configの `[params]` セクションでタイトル、説明を別途宣言するべきであるようす。

各ページについては `description` がヘッダーに存在しないので自動生成されている様子、個別に考えて埋め込んだ方がよさそう。
